import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Footer from "./components/footer/Footer";
import Navigation from "./components/navigation/Navigation";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <header className={styles.header}>
        <div className={styles.navigation}>
          <Navigation/>
        </div>
        <div className={styles.principalText}>
          <h1 className={styles.principalTitle}> Sabores que Abraçam!!</h1>
          <p className={styles.text}> Descubra receitas que trazem o aconchego de casa para a sua mesa. Explore pratos que alimentam o corpo e aquecem o coração. </p>
        </div>
      </header>
    <Footer/>
    </>
  );
}
