import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Footer from "./components/footer/Footer";
import Navigation from "./components/navigation/Navigation";
import { Height } from "@mui/icons-material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <header style={{backgroundImage: "url('/img/BackgroundHeader.png')", height: "100vh", backgroundSize: "cover", backgroundPosition: "center", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
    <div style={{ width: "100%" }}>
      <Navigation />
    </div>
      <div style={{flex: 1, display: "flex",
      flexDirection: "column", alignItems: "center", justifyContent: "center",width:"100vh", gap:"5vh"}}>
        <h1 style={{fontFamily: "Playwrite US Trad",
fontSize: "48px", fontWeight: "400", lineHeight: "92.74px", textAlign: "center", textUnderlinePosition: "fromFont", textDecorationSkipInk: "none"
}}>Sabores que Abraçam!!</h1>
        <p style={{fontFamily: "Work Sans", fontSize: "20px", fontWeight: "400", lineHeight: "23.46px", textAlign: "center", textUnderlinePosition: from-font, textDecorationSkipInk: none}}>Descubra receitas que trazem o aconchego de casa para a sua mesa. Explore pratos que alimentam o corpo e aquecem o coração.</p>
      </div>
    </header>
    <Footer/>
    </>
  );
}
